language: go
go:
  - 1.11.x
install:
  - go get GitHub.com/goohugoio/hugo
script:
  - mkdir -p themes/beatifulhugo && git clone https://GitHub.com/halogenica/beatifulhugo.git themes/beatifulhugo
  - hugo --theme beatifulhugo

deploy:
  provider: pages
  skip_cleanup: true
  GitHub_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
